### PR TITLE
Added support for 11.86 gogs

### PR DESCRIPTION
**Pull request by imreallyliam**

### CODE REVIEW

**Comment by imreallyliam** [comment]
Just tested the patch, it works.

**Comment by Josue-T** [comment]
Well,

I don't mind to upgrade this app, but as the maintener I prever we migrate to gitea. Did you try the migration available here : https://framagit.org/YunoHost-Apps/gitea_ynh/merge_requests/38

**Comment by imreallyliam** [comment]
Currently, I don't see a difference between Gitea and Gogs, well one large enough to migrate.

**Comment by Josue-T** [comment]
Ok,

Are you interested to be the maintainer of this app ?

**Comment by xeu100** [comment]
I'd love to help keep this project going.

**Comment by imreallyliam** [comment]
After further reviewing the Gitea vs Gogs comparison, I'm wondering how the migration works. Upgrading with the URL in its place doesn't work and I'm unable to upgrade the system.

**Comment by Josue-T** [comment]
Ok, well, mybe framagit is not aready supported for update from specific URL. You can also download the archive and after do the upgrade with the file (with the option `-f`).

**Comment by imreallyliam** [comment]
Migration went okay, the system didn't add a service to the service area and it didn't update the name from Gogs to gitea, some updating using the command once installed fixed that.

**Pull request closed without merging**
